### ISSUE TITLE
Error: the first argument must be ActivityPub::Activity or Expression, not School::Expression when running ktistec

### ISSUE THREAD

**Issue by wychwitch** [toddsundsted/ktistec#13]
Locally, running ktistec works just fine! However on my server I'm getting the following error:

```
➜ LOG_LEVEL=INFO crystal run src/ktistec/server.cr
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'finished'

Code in src/utils/compiler.cr:118:5

 118 | macro finished
       ^
Called macro defined in src/utils/compiler.cr:118:5

 118 | macro finished

Which expanded to:

 > 65 | 
 > 66 |               raise LinkError.new(self, "too many arguments") if arguments.size != 2
 > 67 |               School::BinaryPattern.new(ContentRules::IsAddressedTo, arguments[0], arguments[1])
                                            ^--
Error: the first argument must be ActivityPub::Activity or Expression, not School::Expression
```

I'm not sure what's causing this;; if needed I can paste the full error trace if you need! 

I'm running this on debian, and I installed crystal using homebrew!

**Comment by wychwitch** [comment]
It just occurred to me that I tried this on the main branch! Tomorrow I'll try this on dist

**Comment by toddsundsted** [comment]
@wychwitch yes use dist. i incorrectly committed shards.lock to main a short time ago, and main is now pinned to the wrong version of one of the libraries. i have changes that i am just about to commit, which will fix that, but in the meantime dist is better (generally dist is always going to be more stable, since i run my own instance off of dist).
