### ISSUE TITLE
Missing notifications in 2.0.0-9

### ISSUE THREAD

**Issue by JayVii** [toddsundsted/ktistec#83]
Since upgrading to 2.0.0-9 (In Particular c215fecff8588e7f0d07a9d2b67855ae6a91c44c on the `dist` branch), I noticed that a bunch of notifications are being accounted for (missing from the notifications view). This does not affect all types of notifications. Follow-requests still seem to come through, but replies on posts of mine are missing completely (e.g. I didn't get a notification for our conversation under your post yesterday [I do not want to link it here, unless it is needed for debugging]).

I tried to `grep` logs from that time, but didn't see anything out of the ordinary. Any ideas?

**Comment by JayVii** [comment]
Uh oh, it might be an issue on my end.

It seems that I misconfigured the filter-settings. Because before 2.0.0-9 random replies from people in my timeline to other people would show up in my feed, I filtered posts starting with `@`. The new "Don't include replies" timeline feature makes this obsolete. I suppose filters are also applied to notifications?

**Comment by toddsundsted** [comment]
i did make changes to prevent redundant notifications from showing up. before, if you were following a tag, and several people shared a post with that tag, you'd get notified each time. now, you only get a notification for a hashtag or mention once.

but that doesn't sound like your problem. i feel like i have been seeing notifications for replies recently.

filters are applied pretty early, so that definitely could be part of the problem. try removing the filters. i'm happy to send tests posts back and forth to try to reproduce this.

in the log entry, are those failures to my specific ktistec instance, or just generally failures?

**Comment by JayVii** [comment]
I removed the filter and sent you a message.

I got a few "failed to deliver" in my logs. Almost all of them mention accounts that do not exist anymore (looks like they are still in my follower/following lists?). Your account is listed twice. On the 21st and 28th November. Probably not an issue, I guess

**Comment by JayVii** [comment]
Looks like we both got notifications during the test, hence it must have been my filter rule. Sorry for the noise!
